#%RAML 1.0 DataType
type: array
items:
  type: object
  properties:
    order_id:
      type: number
      required: true
    customer_name:
      type: string
      required: true
    product:
      type: string
      required: true
    customer_address:
      type: string
      required: true
    customer_contact:
       type: number
       required: true
    order_type: 
      type: string
      required: true
    regionOfSale:
      type: string
      required: true
    orderValue:
      type: string
      required: true