#%RAML 1.0 Trait
responses:
  401:
    body:
      application/json:
        type: errorResponses
        example: !include ../examples/errorResponses/errorResponse-401.json
  408:
    body:
      application/json:
        type: errorResponses
        example: !include ../examples/errorResponses/errorResponse-408.json
  429:
    body:
      application/json:
        type: errorResponses
        example: !include ../examples/errorResponses/errorResponse-429.json
  504:
    body:
      application/json:
        type: errorResponses
        example: !include ../examples/errorResponses/errorResponse-504.json
          
          
  