#%RAML 1.0
title: sa1001-orders-sapi
description: sa1001-orders-sapi manages the records in DB
version: v1
baseUri: /api/sys/v1
mediaType: 
- application/json
protocols: [HTTP,HTTPS]
types:
  postOrdersRequestDataType: !include /dataTypes/requests/postOrdersDataType.raml
  postOrdersResponseDataType: !include dataTypes/responses/postOrdersDataType.raml
  getOrderResponseDataType: !include dataTypes/responses/getOrdersDataType.raml
  errorResponses: !include dataTypes/errorResponses/errorResponse.raml

traits:
  clinetCredentils: !include traits/clientCredentials.raml
  allErrorResponses: !include traits/errorResponses.raml

resourceTypes:
  ordersResourceType: !include resourceTypes/ordersResourceType.raml
/orders:
  is:
    [clinetCredentils, allErrorResponses]
  type:
    ordersResourceType

  